"""create detection_logs table

Revision ID: f74eefe3b33c
Revises: 
Create Date: 2026-07-22 17:27:36.439169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f74eefe3b33c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('detected', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bbox_x1', sa.Float(), nullable=True),
    sa.Column('bbox_y1', sa.Float(), nullable=True),
    sa.Column('bbox_x2', sa.Float(), nullable=True),
    sa.Column('bbox_y2', sa.Float(), nullable=True),
    sa.Column('gap_center_x', sa.Float(), nullable=True),
    sa.Column('gap_center_y', sa.Float(), nullable=True),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('read_time', sa.Float(), nullable=True),
    sa.Column('decode_time', sa.Float(), nullable=True),
    sa.Column('predict_time', sa.Float(), nullable=True),
    sa.Column('process_time', sa.Float(), nullable=True),
    sa.Column('total_time', sa.Float(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_logs_id'), 'detection_logs', ['id'], unique=False)
    op.create_index(op.f('ix_detection_logs_request_id'), 'detection_logs', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_logs_request_id'), table_name='detection_logs')
    op.drop_index(op.f('ix_detection_logs_id'), table_name='detection_logs')
    op.drop_table('detection_logs')
    # ### end Alembic commands ###
